# Generated by Django 5.1.7 on 2025-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
